### ISSUE TITLE
How animate multiple markers at the same time?

### ISSUE THREAD

**Issue by GabrielZulian** [gauris26/flutter_animarker#1]
Hi, i have a question.

Is it possible to animate an array of markers and not only one?
The examples only show one sourceId for the markerId and i cant get the reference in the stream subscription, because the LatLngDelta model only have from, to, and rotation attributes.

**Comment by vipinnegi90** [comment]
@GabrielZulian Were you able to animate multiple markers? I have the same requirement in my project.

**Comment by gauris26** [comment]
I'll be publishing the new update to animate and reference multiple markers at the same time. Thank you for the feedback guys.

**Comment by gauris26** [comment]
@vipinnegi90 @GabrielZulian I already added the requested functionality using a marker ID property. Can you try it?
