### ISSUE TITLE
camera going to marker after new latlng

### ISSUE THREAD

**Issue by carlosmoretti** [gauris26/flutter_animarker#10]
when I add new latlng, the camera position goes to the new marker. Have some method to disable this and keep the camera position at user location?

tks!!!

**Comment by gauris26** [comment]
Hi Carlos,

I added a new flag to control this behavior. Please try the last pre-release version (3.1.3-beta.2) just published.

`shouldAnimateCamera` set false for preventing animate Google Maps camera.
