### ISSUE TITLE
ontap event is not working

### ISSUE THREAD

**Issue by carlosmoretti** [gauris26/flutter_animarker#11]
when i call the ontap function, i've getting this error
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Unknown marker ID "13" in onTap

have some way to use ontap in this?

tks!

**Comment by gauris26** [comment]
I'll need to figure out how to solve the lack of function serializing, specifically Marker's callbacks.

Thank you for raising the issue.

**Comment by carlosmoretti** [comment]
animarker initializer
> Animarker(
            curve: Curves.linear,
            useRotation: false,
            duration: Duration(milliseconds: 5500),
            mapId: controller.future.then<int>((value) => value.mapId), //Grab Google Map Id
            markers: markers.values.toSet(),
            shouldAnimateCamera: false,
            key: mapKey,
            child: GoogleMap(
              myLocationEnabled: true,
              mapType: MapType.normal,
              initialCameraPosition: cameraPosition,
              onMapCreated: (gController) => controller.complete(gController), //Complete the future GoogleMapController
            ),
          ),

marker creator (I'd try using ripplemarker too, but got same error)
> Future<Marker> createMarker(MarkerId marcador, LatLng posicao, VendedorDto vendedor) async {
    Uint8List icone = await this.getBytesFromAsset("assets/images/icon_map.png", 75);
    return Marker(
      markerId: marcador,
      position: posicao,
      infoWindow: InfoWindow(title: vendedor.nomeVendedor),
      icon: BitmapDescriptor.fromBytes(icone),
      onTap: () => print("Olá Mundo")
    );
  }

newLocationUpdate method on root of widget (that calls the marker creator).
> void newLocationUpdate(MarkerId marcador, LatLng latLng, VendedorDto dto) {
>     _mapController.createMarker(marcador, latLng, dto)
>       .then((value) {
>         setState(() {
>           markers[marcador] = value;
>         });
>       });
>   }

the ontap method just works if I pass markers to GoogleMap widget

> Animarker(
>             curve: Curves.linear,
>             useRotation: false,
>             duration: Duration(milliseconds: 5500),
>             mapId: controller.future.then<int>((value) => value.mapId), //Grab Google Map Id
>             markers: markers.values.toSet(),
>             shouldAnimateCamera: false,
>             key: mapKey,
>             child: GoogleMap(
>               markers: markers.values.toSet(),
>               myLocationEnabled: true,
>               mapType: MapType.normal,
>               initialCameraPosition: cameraPosition,
>               onMapCreated: (gController) => controller.complete(gController), //Complete the future GoogleMapController
>             ),
>           ),

but passing markers to google map widget, the marker duplicate..

**Comment by gauris26** [comment]
I published a new version pre-release version fixing the issue, although you will still get the error from Google Map widget. I need to figure out to prevent it.

```dart
Marker(
    ...
    onTap: () {
    print('Tapped!');
    },
    ...
  )
```

Thank you, Carlos, for helping to identify these issues. I'm looking forward to you feedback.

Regards,

**Comment by YassineChe** [comment]
@gauris26 , The same issue for `onTap` of `InfoWindow`.

The issue will disappear if you duplicate `markers` attribute for `GoogleMap` widget ..
This is just a temporary solution, waiting for your response!

Best regards.

**Comment by anish769** [comment]
Unhandled Exception: Unknown marker ID "99" in InfoWindow onTap
![image](https://user-images.githubusercontent.com/86772702/183892836-ee51dc2c-070a-41d9-8c7a-ea1e4ad42c07.png)

**Comment by anish769** [comment]
My ontap function is not working in animarker
