### ISSUE TITLE
The marker isn't drawed

### ISSUE THREAD

**Issue by neoacevedo** [gauris26/flutter_animarker#7]
I followed the example, and the marker isn't displayed in the map.

**Comment by gauris26** [comment]
The plugin assumes you already have the marker drawn in the map. So, please be sure you can place markers in your map first. 

Nevertheless, I will be pushing a few dependencies upgrades to the example project, it may help you.

Regards,

**Comment by neoacevedo** [comment]
I followed the example in the repo:

```dart 
subscription =
        _latLngStream.getLatLngInterpolation().listen((LatLngDelta delta) {
      LatLng from = delta.from;
      print("To: -> ${from.toJson()}");
      LatLng to = delta.to;
      print("From: -> ${to.toJson()}");
      double angle = delta.rotation;
      print("Angle: -> $angle");
      //Update the animated marker
      setState(() {
        Marker sourceMarker = Marker(
          markerId: sourceId,
          rotation: delta.rotation,
          position: LatLng(
            delta.from.latitude,
            delta.from.longitude,
          ),
        );
        _markers[sourceId] = sourceMarker;
      });

      if (polygon.isNotEmpty) {
        //Pop the last position
        _latLngStream.addLatLng(polygon.removeLast());
      }
    });
```

But the marker is never displayed. Later, I tried the the location plugin, and it neither worked, then I left my code as before to use this plugin, and the marker was displayed again.

**Comment by gauris26** [comment]
I will be publishing a new update with a clearer example and the animation of multiple markers at the same time. Be aware.

Thank you for the feedback.

**Comment by gauris26** [comment]
> I followed the example in the repo:
> 
> ```dart
> subscription =
>         _latLngStream.getLatLngInterpolation().listen((LatLngDelta delta) {
>       LatLng from = delta.from;
>       print("To: -> ${from.toJson()}");
>       LatLng to = delta.to;
>       print("From: -> ${to.toJson()}");
>       double angle = delta.rotation;
>       print("Angle: -> $angle");
>       //Update the animated marker
>       setState(() {
>         Marker sourceMarker = Marker(
>           markerId: sourceId,
>           rotation: delta.rotation,
>           position: LatLng(
>             delta.from.latitude,
>             delta.from.longitude,
>           ),
>         );
>         _markers[sourceId] = sourceMarker;
>       });
> 
>       if (polygon.isNotEmpty) {
>         //Pop the last position
>         _latLngStream.addLatLng(polygon.removeLast());
>       }
>     });
> ```
> 
> But the marker is never displayed. Later, I tried the the location plugin, and it neither worked, then I left my code as before to use this plugin, and the marker was displayed again.

Can you try the new update to the plugin.

**Comment by neoacevedo** [comment]
I don't need this plugin in my project.  I apologize.
