### ISSUE TITLE
Working Example

### ISSUE THREAD

**Issue by thisdotbunik** [gauris26/flutter_animarker#8]
Hello!
Can you provide me with a working simple example, please?

**Comment by gauris26** [comment]
I'm working currently in new version, using Widget and reactive way. Will support multiple markers at same time, ripple effect, curves, listeners and better performance.

This week, I'll be pushing the new beta version, have a look:

Animarker(
  mapId: 0,
  performanceMode: PerformanceMode.better,
  duration: Duration(milliseconds: 2000),
  markers: <Marker>{
		RippleMarker(
		  markerId: MarkerId("MarkerId1"),
		  position: startPosition,
		  ripple: true,
		),
		Marker(
		  markerId: MarkerId("MarkerId3"),
		  position: startPosition2,
		)
  },
  child: GoogleMap(
	mapType: MapType.normal,
	cameraPosition(
      target: LatLng(18.488141761655367, -69.9591860021479),
      zoom: 15,
    ),
  ),
)
